#!/usr/bin/env python3
"""make_fixtures -- emit this repo's LIFELIKE test fixtures, so a real record cannot be one.

WHY A GENERATOR AT ALL
----------------------
`.dataclass.json` has declared a FIXTURE class since the boundary was armed, and this repo's
fixture list was EMPTY, which meant check 2 in tools/data_boundary.py iterated zero times and
proved nothing. Meanwhile `skills/daily-hotspots/tests/fixtures/watchlist.with-sources.json` was a
trimmed copy of the operator's LIVE private watchlist: same track tuning, same source lane tuning,
same daily cron, same local timezone, same quiet hours. It carried a `_note` calling itself a
"PARSE-ONLY TEST FIXTURE (not live config)", and that sentence was the entire control. It was also
true and useless at the same time: the file really was only parsed by tests, and it really did
publish a person's daily schedule and their machine's timezone.

The rule that fixes this is mechanical, not attentional. A fixture must be byte-identical to what
this generator emits, and a generator cannot reproduce a real record. So the next person who
"just pastes in the real config, it is easier" fails at commit time instead of at audit time,
months later, in someone else's report.

WHAT IS SYNTHETIC HERE AND WHAT IS NOT
-------------------------------------
Not everything in a config file is somebody's life, and blanking the whole surface would destroy
the fixture's reason to exist (it is the worked example of the source-coverage watchlist surface
that `reference/collect.md` points readers at). The split:

  KEPT, because it is TOOL material and identical to lib.DEFAULT_CONFIG anyway
      tracks, focus_topics, exclude, machine_types, scoring weights and floors

  KEPT, because it is a fact about a PUBLIC third-party surface, not about a person
      lane names (linux.do, v2ex, ...), fetch method per lane, the RSS routes those sites
      publish, the site's own category name, the thresholds the tests assert on

  SYNTHESIZED, because it encoded the operator
      the daily cron and its timezone, the quiet hours, the subreddit picks, the CN feed URL and
      publisher, the per-lane node keep/drop picks, and every `_note` that recorded what happened
      on a real run of theirs

Every synthesized value is drawn from the synthetic namespace (example.com, `r/example-*`,
`example-node-*`, UTC) so it is self-evidently fake standing next to a real one, and the file
carries a canary field naming this generator.

  python tools/make_fixtures.py --out <dir>     write every fixture into <dir> (flat, by basename)
  python tools/make_fixtures.py --install       write them to their tracked locations in this repo
  python tools/make_fixtures.py --check         exit 1 if any tracked fixture has drifted

data_boundary.py check 2 calls the `--out` form and compares bytes. Stdlib only.
"""
import argparse
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Where each generated fixture belongs in the tree. The KEY is the basename, because that is what
# data_boundary's check 2 looks for in the --out directory.
TARGETS = {
    "watchlist.with-sources.json":
        "skills/daily-hotspots/tests/fixtures/watchlist.with-sources.json",
}

CANARY = ("SYNTHETIC FIXTURE, GENERATED BY tools/make_fixtures.py. Do not hand-edit and never "
          "paste a real watchlist here: data_boundary.py check 2 compares this file byte for byte "
          "against the generator, and a real record cannot be regenerated. Change the generator.")


def watchlist_with_sources():
    """The source-coverage watchlist surface (design spec 5.1), as a synthetic worked example.

    The values the test suite actually asserts on are pinned here with a comment saying which
    property depends on them, so the next person to regenerate this knows which numbers are load
    bearing and which are decoration.
    """
    return {
        "schema_version": 1,
        "_synthetic": CANARY,
        "_note": ("Parse-only worked example of the source-coverage watchlist surface: the "
                  "community source rows, sources.twitterapi.roster_ref + min_faves_rostered, and "
                  "the community_pulse + yield tuning blocks. Deep-merges over DEFAULT_CONFIG."),
        # ---------------------------------------------------------------- TOOL material (defaults)
        "tracks": [
            {"id": "ai-agents", "label": "AI agents / dev tooling", "weight": 1.3,
             "keywords": ["agent", "agents", "mcp", "llm", "rag", "vibe coding", "copilot",
                          "fine-tune", "inference", "prompt", "vector", "embedding"],
             "enabled": True},
            {"id": "dev-tools", "label": "Developer tools", "weight": 1.1,
             "keywords": ["sdk", "cli", "framework", "devtool", "ci", "observability", "database",
                          "api", "open source", "self-host"], "enabled": True},
            {"id": "saas-niche", "label": "Vertical SaaS", "weight": 1.0,
             "keywords": ["saas", "workflow", "automation", "crm", "billing", "compliance",
                          "vertical", "b2b"], "enabled": True},
            {"id": "fintech-crypto", "label": "Fintech / Crypto", "weight": 1.0,
             "keywords": ["defi", "yield", "stablecoin", "onchain", "wallet", "payments",
                          "fintech", "trading", "tokeniz"], "enabled": True},
            {"id": "consumer-social", "label": "Consumer / social", "weight": 0.9,
             "keywords": ["creator", "social", "consumer", "mobile app", "community",
                          "marketplace"], "enabled": True},
            {"id": "hardware-iot", "label": "Hardware / IoT", "weight": 0.9,
             "keywords": ["hardware", "iot", "device", "robot", "sensor", "wearable", "edge"],
             "enabled": True},
        ],
        "focus_topics": ["open-source replacing paid API", "solo-founder-doable",
                         "underpriced arbitrage"],
        "exclude": ["crypto pump", "memecoin", "mlm", "nsfw", "giveaway airdrop"],
        "machine_types": ["tool-saas", "marketplace", "media", "service", "hardware", "arbitrage",
                          "oss-monetization"],
        "scoring": {
            "weights": {"track_fit": 0.20, "timing": 0.25, "feasibility": 0.20,
                        "competition": 0.15, "executability": 0.20},
            "min_score_to_archive": 55,
            "min_score_to_push": 70,
            "min_score_to_deepdive": 80,
            "min_independent_sources": 2,
            "freshness_half_life_h": 72,
            "freshness_gravity": 1.8,
            "dedup_cosine_threshold": 0.83,
            "dedup_simhash_hamming": 3,
            "lookback_days": 7,
            "resurface_score_jump": 15,
            "samples_cap": 30,
            "fading_quiet_days": 5,
        },
        # ------------------------------------------------------------------------- source lanes
        "sources": {
            # enabled:false is asserted by test_guardrails (a lane that silently degraded is marked
            # dead rather than deleted, so the reason survives).
            "trend-pulse": {"enabled": False, "weight": 1.0, "max_items": 40,
                            "_dead": "lane returned success with an empty payload; marked dead "
                                     "rather than removed, per spec 6"},
            "gdelt": {"enabled": True, "weight": 0.9},
            "hackernews": {"enabled": True, "weight": 1.1},
            # SYNTHETIC subreddit picks. The real ones are a person's reading list.
            "reddit": {"enabled": True, "subreddits": ["r/example-alpha", "r/example-beta"],
                       "weight": 0.8, "auth_tier": "login",
                       "_note": "authenticated tier escapes the anonymous IP block; the scraped "
                                "route is demoted to a best-effort secondary"},
            # min_faves_rostered = 25 is load bearing: test_attribution pins the pre-viral catch on
            # a rostered floor BELOW the keyword-search floor of 500.
            "twitterapi": {"enabled": True, "weight": 1.0, "roster_ref": "roster.json",
                           "min_faves_rostered": 25,
                           "_note": "rostered handles pull with a LOW faves floor to catch "
                                    "pre-viral posts; roster_ref points at the companion "
                                    "roster.json; the broad keyword search stays for open "
                                    "discovery"},
            # routes / fetch / keep_categories are load bearing: test_guardrails asserts the lane
            # uses only the two allowed .rss routes and brightdata, and the community-lane KEEP
            # test needs the site's own category name to be in keep_categories.
            "linux.do": {"enabled": True, "weight": 1.0, "fetch": "brightdata",
                         "routes": ["/latest.rss", "/top.rss?period=daily"],
                         "keep_categories": ["前沿快讯", "开发调优"],
                         "_note": "RSS only (injection-free); plain HTTP is 403 behind the CDN; "
                                  "respect Content-Signal ai-train=no, read-only reference digest"},
            # fetch=webfetch is load bearing (test_guardrails), and so are the node lists: the
            # sibling parse fixture sources/v2ex-hot.json carries nine items across seven of that
            # site's PUBLIC node slugs, and test_attribution pins the filter at exactly 6 kept / 3
            # dropped. These are a public taxonomy, not a reading list, so they stay real.
            "v2ex": {"enabled": True, "weight": 0.9, "fetch": "webfetch",
                     "routes": ["/api/topics/hot.json", "/api/topics/latest.json"],
                     "keep_nodes": ["create", "programmer", "cloud", "geek"],
                     "drop_nodes": ["jobs", "all4all", "flamewar"],
                     "_note": "keyless JSON API; the scraping proxy returns empty for this host, "
                              "so it must be fetched directly"},
            # SYNTHETIC feed. The real row names a specific publisher the operator follows.
            "cn-feeds": {"enabled": True, "weight": 0.8, "fetch": "webfetch",
                         "feeds": [{"source": "example-cn-feed",
                                    "url": "https://feeds.example.com/cn/feed",
                                    "label": "示例中文源"}],
                         "_note": "keyless RSS; pick the highest signal-to-noise publisher and "
                                  "verify every feed URL at scan time"},
            "product-hunt": {"enabled": True, "weight": 1.0},
            "arxiv": {"enabled": True, "weight": 0.9},
            "google-news-trends": {"enabled": True, "weight": 0.6},
            # enabled:false is asserted by test_guardrails.
            "duckduckgo": {"enabled": False, "_hard_disabled": "hangs; banned"},
        },
        # max_per_day=8 and the label string are load bearing (test_community_pulse).
        "community_pulse": {
            "enabled": True,
            "max_per_day": 8,
            "label": "⚠️ 单源未验证 · 社区小道消息",
            "community_sources": ["linux.do", "v2ex", "example-cn-feed"],
            "rank_by": ["freshness", "community_heat"],
            "_note": ("dual-track Track 2 (spec 7): single-origin community signals, link plus a "
                      "one-line why, NO score, NO deep-dive; cross-day dedup reuses the ledger"),
        },
        "yield": {
            "window_days": 30,
            "floor": 0,
            "prune_after_weeks": 2,
            "min_history_days": 7,
            "propose_add_min_count": 2,
            "pre_viral_faves_threshold": 500,
            "noisy_pull_min": 10,
            "noisy_yield_max": 0.1,
            "_note": ("signal-yield engine thresholds (spec 8/9); methodology constant, thresholds "
                      "tunable; report-only until min_history_days of real history"),
        },
        "delegation": {"market-intel": {"enabled": True,
                                        "trigger": "score>=80 OR track in [fintech-crypto]",
                                        "scale": "standard", "daily_cap": 4}},
        # SYNTHETIC schedule. The real rows publish when the operator's machine is idle and which
        # timezone they live in, which is exactly the kind of thing a fixture has no business
        # carrying. UTC and a midnight cron are obviously nobody's actual routine.
        "push": {"channel": "discord-relay", "max_per_day": 5, "quiet_hours_tz": "UTC",
                 "quiet": ["00:00", "06:00"]},
        "schedule": {"cron": "0 0 * * *", "tz": "UTC"},
    }


BUILDERS = {
    "watchlist.with-sources.json": watchlist_with_sources,
}


def render(name):
    """The bytes for one fixture. ONE code path, so `--install` and `--out` cannot disagree."""
    return (json.dumps(BUILDERS[name](), ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def _write(path, blob):
    d = os.path.dirname(path)
    if d:
        os.makedirs(d, exist_ok=True)
    with open(path, "wb") as f:
        f.write(blob)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate this repo's synthetic test fixtures.")
    ap.add_argument("--out", help="write every fixture into this directory, named by basename")
    ap.add_argument("--install", action="store_true",
                    help="write every fixture to its tracked location in this repo")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if a tracked fixture differs from what this generator emits")
    a = ap.parse_args(argv)
    if not (a.out or a.install or a.check):
        ap.error("pick one of --out / --install / --check")

    if a.out:
        for name in BUILDERS:
            _write(os.path.join(a.out, name), render(name))

    if a.install:
        for name, rel in TARGETS.items():
            _write(os.path.join(REPO, rel), render(name))
            print("wrote %s" % rel)

    if a.check:
        bad = 0
        for name, rel in TARGETS.items():
            p = os.path.join(REPO, rel)
            if not os.path.isfile(p):
                print("MISSING   %s" % rel, file=sys.stderr)
                bad += 1
                continue
            live = open(p, "rb").read().replace(b"\r\n", b"\n")
            if live != render(name).replace(b"\r\n", b"\n"):
                print("DRIFTED   %s  (run: python tools/make_fixtures.py --install)" % rel,
                      file=sys.stderr)
                bad += 1
        if bad:
            print("%d fixture(s) do not match the generator. A real record cannot be "
                  "regenerated, so this is either an edit that belongs in the generator or a "
                  "pasted record." % bad, file=sys.stderr)
            return 1
        print("make_fixtures: %d fixture(s) match the generator" % len(TARGETS))
    return 0


if __name__ == "__main__":
    sys.exit(main())
